CREATE DATABASE dbAcademicNotes;

use dbAcademicNotes;

--- Criando banco tabelas

create TABLE STUDENTS 
(
	ID_STUDENT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME_STUDENT varchar(50),
    STATUS_STUDENT BIT    
);

CREATE TABLE STUDENTS_NOTES (
    ID_NOTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VALUE_NOTE DOUBLE,
    ID_STUDENT INT,
    CONSTRAINT FK_STUDENT FOREIGN KEY (ID_STUDENT)
        REFERENCES STUDENTS (ID_STUDENT)
);

INSERT INTO STUDENTS (NAME_STUDENT)
VALUES ("Vinicius Lima");

SELECT * FROM STUDENTS
